# Worksheet Wonder: add the 26 A-Z uppercase letter worksheets to the catalog.
# Run from your website project root (the folder that contains assets/).
$ErrorActionPreference = 'Stop'
$utf8 = New-Object Text.UTF8Encoding($false)
$db = 'assets/js/database.js'
if (-not (Test-Path $db)) { Write-Error "assets/js/database.js not found. Run this script from your website project root."; exit 1 }
$s = [IO.File]::ReadAllText($db, [Text.Encoding]::UTF8)
if ($s -match "ws-abc-a") { Write-Host "Already added - nothing to do."; exit 0 }
$anchor = "id: 'ws-trace-z'"
$i = $s.IndexOf($anchor)
if ($i -lt 0) { Write-Error "Anchor (ws-trace-z) not found in database.js - is this the Worksheet Wonder project?"; exit 1 }
$eol = $s.IndexOf("`n", $i) + 1
$entries = @'
        { id: 'ws-abc-a', title: 'The Letter A (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-a.png', file: 'assets/pdf/uppercase-letter-a.pdf', desc: 'Trace the uppercase letter A with stroke-order guides, say the A words - Apple, Ant, Alligator - and colour the Apple page!' },
        { id: 'ws-abc-b', title: 'The Letter B (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-b.png', file: 'assets/pdf/uppercase-letter-b.pdf', desc: 'Trace the uppercase letter B with stroke-order guides, say the B words - Bear, Ball, Butterfly - and colour the Bear page!' },
        { id: 'ws-abc-c', title: 'The Letter C (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-c.png', file: 'assets/pdf/uppercase-letter-c.pdf', desc: 'Trace the uppercase letter C with stroke-order guides, say the C words - Cat, Car, Cake - and colour the Cat page!' },
        { id: 'ws-abc-d', title: 'The Letter D (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-d.png', file: 'assets/pdf/uppercase-letter-d.pdf', desc: 'Trace the uppercase letter D with stroke-order guides, say the D words - Dog, Duck, Drum - and colour the Dog page!' },
        { id: 'ws-abc-e', title: 'The Letter E (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-e.png', file: 'assets/pdf/uppercase-letter-e.pdf', desc: 'Trace the uppercase letter E with stroke-order guides, say the E words - Elephant, Egg, Eagle - and colour the Elephant page!' },
        { id: 'ws-abc-f', title: 'The Letter F (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-f.png', file: 'assets/pdf/uppercase-letter-f.pdf', desc: 'Trace the uppercase letter F with stroke-order guides, say the F words - Fish, Frog, Flower - and colour the Fish page!' },
        { id: 'ws-abc-g', title: 'The Letter G (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-g.png', file: 'assets/pdf/uppercase-letter-g.pdf', desc: 'Trace the uppercase letter G with stroke-order guides, say the G words - Grapes, Goat, Guitar - and colour the Goat page!' },
        { id: 'ws-abc-h', title: 'The Letter H (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-h.png', file: 'assets/pdf/uppercase-letter-h.pdf', desc: 'Trace the uppercase letter H with stroke-order guides, say the H words - Hat, Horse, House - and colour the Horse page!' },
        { id: 'ws-abc-i', title: 'The Letter I (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-i.png', file: 'assets/pdf/uppercase-letter-i.pdf', desc: 'Trace the uppercase letter I with stroke-order guides, say the I words - Ice cream, Igloo, Insect - and colour the Ice cream page!' },
        { id: 'ws-abc-j', title: 'The Letter J (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-j.png', file: 'assets/pdf/uppercase-letter-j.pdf', desc: 'Trace the uppercase letter J with stroke-order guides, say the J words - Jellyfish, Jet, Jar - and colour the Jellyfish page!' },
        { id: 'ws-abc-k', title: 'The Letter K (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-k.png', file: 'assets/pdf/uppercase-letter-k.pdf', desc: 'Trace the uppercase letter K with stroke-order guides, say the K words - Kite, Kangaroo, Key - and colour the Kite page!' },
        { id: 'ws-abc-l', title: 'The Letter L (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-l.png', file: 'assets/pdf/uppercase-letter-l.pdf', desc: 'Trace the uppercase letter L with stroke-order guides, say the L words - Lion, Lemon, Leaf - and colour the Lion page!' },
        { id: 'ws-abc-m', title: 'The Letter M (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-m.png', file: 'assets/pdf/uppercase-letter-m.pdf', desc: 'Trace the uppercase letter M with stroke-order guides, say the M words - Monkey, Moon, Mango - and colour the Monkey page!' },
        { id: 'ws-abc-n', title: 'The Letter N (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-n.png', file: 'assets/pdf/uppercase-letter-n.pdf', desc: 'Trace the uppercase letter N with stroke-order guides, say the N words - Nest, Nose, Net - and colour the Nest page!' },
        { id: 'ws-abc-o', title: 'The Letter O (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-o.png', file: 'assets/pdf/uppercase-letter-o.pdf', desc: 'Trace the uppercase letter O with stroke-order guides, say the O words - Orange, Owl, Octopus - and colour the Owl page!' },
        { id: 'ws-abc-p', title: 'The Letter P (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-p.png', file: 'assets/pdf/uppercase-letter-p.pdf', desc: 'Trace the uppercase letter P with stroke-order guides, say the P words - Parrot, Penguin, Pizza - and colour the Parrot page!' },
        { id: 'ws-abc-q', title: 'The Letter Q (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-q.png', file: 'assets/pdf/uppercase-letter-q.pdf', desc: 'Trace the uppercase letter Q with stroke-order guides, say the Q words - Queen, Quilt, Quill - and colour the Queen page!' },
        { id: 'ws-abc-r', title: 'The Letter R (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-r.png', file: 'assets/pdf/uppercase-letter-r.pdf', desc: 'Trace the uppercase letter R with stroke-order guides, say the R words - Rabbit, Rainbow, Robot - and colour the Rabbit page!' },
        { id: 'ws-abc-s', title: 'The Letter S (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-s.png', file: 'assets/pdf/uppercase-letter-s.pdf', desc: 'Trace the uppercase letter S with stroke-order guides, say the S words - Sun, Star, Snake - and colour the Sun page!' },
        { id: 'ws-abc-t', title: 'The Letter T (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-t.png', file: 'assets/pdf/uppercase-letter-t.pdf', desc: 'Trace the uppercase letter T with stroke-order guides, say the T words - Tiger, Tree, Turtle - and colour the Tiger page!' },
        { id: 'ws-abc-u', title: 'The Letter U (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-u.png', file: 'assets/pdf/uppercase-letter-u.pdf', desc: 'Trace the uppercase letter U with stroke-order guides, say the U words - Umbrella, Unicorn, Ukulele - and colour the Umbrella page!' },
        { id: 'ws-abc-v', title: 'The Letter V (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-v.png', file: 'assets/pdf/uppercase-letter-v.pdf', desc: 'Trace the uppercase letter V with stroke-order guides, say the V words - Violin, Vase, Van - and colour the Violin page!' },
        { id: 'ws-abc-w', title: 'The Letter W (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-w.png', file: 'assets/pdf/uppercase-letter-w.pdf', desc: 'Trace the uppercase letter W with stroke-order guides, say the W words - Whale, Watermelon, Watch - and colour the Whale page!' },
        { id: 'ws-abc-x', title: 'The Letter X (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-x.png', file: 'assets/pdf/uppercase-letter-x.pdf', desc: 'Trace the uppercase letter X with stroke-order guides, say the X words - Xylophone, X-ray, Xmas tree - and colour the Xylophone page!' },
        { id: 'ws-abc-y', title: 'The Letter Y (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-y.png', file: 'assets/pdf/uppercase-letter-y.pdf', desc: 'Trace the uppercase letter Y with stroke-order guides, say the Y words - Yo-yo, Yak, Yacht - and colour the Yak page!' },
        { id: 'ws-abc-z', title: 'The Letter Z (Uppercase)', grade: 'kindergarten', subject: 'english', topic: 'Alphabet', pages: 1, price: 0, rating: 4.9, downloads: 0, thumb: IMG + 'worksheets/letter-z.png', file: 'assets/pdf/uppercase-letter-z.pdf', desc: 'Trace the uppercase letter Z with stroke-order guides, say the Z words - Zebra, Zoo, Zipper - and colour the Zebra page!' },
'@
$s = $s.Substring(0, $eol) + $entries + "`n" + $s.Substring($eol)
[IO.File]::WriteAllText($db, $s, $utf8)
Write-Host "Done - 26 worksheets added to database.js"
